services:
  silly-demo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/pkg/mod
    ports:
      - "8080:8080"
    environment:
      - GO111MODULE=on
      - AIR_WATCH_DELAY=500ms
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - silly-demo

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql

volumes:
  db_data: